services:
  todo-app:
    build: .
    image: todo-app
    container_name: todo-app-container
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - DB_FILE_PATH=/app/server_api/data/db.json
    volumes:
      - todo-data:/app/server_api/data

volumes:
  todo-data:
